### ISSUE TITLE
Can't connect to the vagrant with ssh

### ISSUE THREAD

**Issue by benja-M-1** [fansible/ansible-provisioning-tywin#15]
I followed the instruction on the README but the `ansible-playbook` failed 
<img width="1678" alt="capture d ecran 2015-11-08 a 16 38 02" src="https://cloud.githubusercontent.com/assets/212269/11021095/3fcfcf22-8637-11e5-926c-b2d8b9089680.png">

As my public key is not on the vagrant user's `/home/vagrant/.ssh/authorized_keys` file nor ansible uses vagrant's ssh key Ansible isable to connect on the vm.

I can't figure out how to make it work :(

**Comment by MaximeThoonsen** [comment]
Yes. I will update the README
