### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by flavianh** [fansible/ansible-provisioning-tywin#27]
- Missing `php5-sqlite` under php_pakages in `/devops/provisioning/roles/fansible-roles/ubuntu-php/defaults/main.yml`
- **There is no `default` file in `/etc/nginx/sites-available`** <- Actually the error I get is not linked to that, since there is a conf.d/main.conf file  which configures nginx for symfony. 
- There is a broken symbolic link from `/etc/nginx/sites-enables/default` pointing to `/etc/nginx/sites-available/default`

Ansible version: ansible 2.0.1.0

**Comment by MaximeThoonsen** [comment]
Thanks @traxair . I'll work on it asap ;)

**Comment by MaximeThoonsen** [comment]
done
