### ISSUE TITLE
Roles are generated in a directory 'fansible-roles' which is not found by ansible-playbook

### ISSUE THREAD

**Issue by cRicateau** [fansible/ansible-provisioning-tywin#38]
When I generate the provisioning and run: ansible-playbook -i devops/provisioning/hosts/vagrant devops/provisioning/playbook.yml 

I have the error:
ERROR: cannot find role in /home/clementrp/Projects/formation/test/devops/provisioning/roles/ubuntu-apt or /home/clementrp/Projects/formation/test/devops/provisioning/ubuntu-apt or /etc/ansible/roles/ubuntu-apt

Because all roles a created in a folder 'fansible-roles' 

It should be told in the documentation to create a file ansible.cfg at the root of the project with the following content: 
[defaults]
`roles_path = devops/provisioning/roles/fansible-roles`

**Comment by MaximeThoonsen** [comment]
@cRicateau tywin already creates the ansible.cfg file. Maybe I should add that we need to run the script from where the ansible.cfg file is located ?
